[project]
name = "llm-index-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bm25s>=0.2.14",
    "datasets>=4.5.0",
    "google-genai>=1.63.0",
    "litellm>=1.81.14",
    "pystemmer>=3.0.0",
    "python-dotenv>=1.2.1",
]
